// Generated by CoffeeScript 1.6.2
(function() {
  var Config, action, blindUp, createDeck, dealPlayersHands, gameStart, getActionPlayer, getInfo, getState, getTableInfo, intervalTime, join, level, playersCount, shuffleArray, shufflePlayers, state, structure, tables;

  Config = require('../config');

  tables = {};

  playersCount = 0;

  structure = Config.getStructure();

  intervalTime = Config.getIntervalTime();

  state = 'waiting';

  level = 0;

  join = function(name, key, socketId) {
    if (!tables[0] || tables[0].players.length < 10) {
      if (!tables[0]) {
        tables[0] = {};
      }
      if (!tables[0].players) {
        tables[0].players = [];
      }
      tables[0].players[tables[0].players.length] = {
        id: playersCount,
        name: name,
        key: key,
        socketId: socketId,
        isActive: false,
        win: null,
        tie: null,
        hand: []
      };
    }
    return playersCount += 1;
  };

  gameStart = function() {
    var bbPosition, i, sbPosition, stack, table, tableId, _i, _ref;

    level = 0;
    stack = Config.getStack();
    for (tableId in tables) {
      table = tables[tableId];
      table.players = [].concat(shufflePlayers(table.players));
      table.dealerButton = Math.floor(Math.random() * table.players.length);
      table.playedHandCount = 0;
      table.actionCount = 0;
      table.lastBet = 0;
      table.pot = 0;
      for (i = _i = 0, _ref = table.players.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        table.players[i].stack = 10000;
      }
      sbPosition = (table.dealerButton + 1) % table.players.length;
      bbPosition = (table.dealerButton + 2) % table.players.length;
      table.pot += Number(structure[level] / 2);
      table.players[sbPosition].stack -= Number(structure[level] / 2);
      table.pot += structure[level];
      table.players[bbPosition].stack -= structure[level];
      dealPlayersHands(tableId);
      table.actionPlayerSeat = (table.dealerButton + 3) % table.players.length;
    }
    setTimeout(function() {
      return blindUp();
    }, intervalTime);
    return state = 'gaming';
  };

  getInfo = function() {
    var info, key, value;

    info = {
      state: state,
      level: level,
      tables: {}
    };
    for (key in tables) {
      value = tables[key];
      info.tables[key] = {
        pot: tables[key].pot,
        lastBet: tables[key].lastBet,
        dealerButton: tables[key].dealerButton,
        players: tables[key].players
      };
    }
    return info;
  };

  getState = function() {
    return state;
  };

  getTableInfo = function(tableId) {
    var key, player, tableInfo, _ref;

    tableInfo = {
      state: state,
      level: level,
      pot: tables[tableId].pot,
      dealerButton: tables[tableId].dealerButton,
      players: []
    };
    _ref = tables[tableId].players;
    for (key in _ref) {
      player = _ref[key];
      tableInfo.players[key] = {
        name: player.name,
        stack: player.stack,
        isActive: player.isActive
      };
    }
    return tableInfo;
  };

  getActionPlayer = function(tableId) {
    return tables[tableId].players[tables[tableId].actionPlayerSeat];
  };

  action = function(data, callback) {
    var actionPlayerSeat, amount, key, tableId;

    key = data.key;
    action = data.action;
    amount = data.amount;
    tableId = 0;
    if (key === tables[tableId].players[tables[tableId].actionPlayerSeat].key) {
      actionPlayerSeat = tables[tableId].actionPlayerSeat;
      switch (action) {
        case 'fold':
          tables[tableId].players[actionPlayerSeat].isActive = false;
          callback({
            status: 'ok',
            message: 'got fold.'
          });
          break;
        case 'call':
          tables[tableId].pot += tables[tableId].lastBet;
          tables[tableId].players[actionPlayerSeat].stack -= tables[tableId].lastBet;
          callback({
            status: 'ok',
            message: 'got call.'
          });
          break;
        case 'raise':
          if (amount < tables[tableId].lastBet * 2) {
            amount = tables[tableId].lastBet * 2;
          }
          tables[tableId].pot += amount;
          tables[tableId].players[actionPlayerSeat].stack -= amount;
          callback({
            status: 'ok',
            message: 'got raise ' + amount
          });
      }
      return tables[tableId].actionPlayerSeat += 1;
    } else {
      return callback('ignroe');
    }
  };

  module.exports = {
    join: join,
    getInfo: getInfo,
    gameStart: gameStart,
    getState: getState,
    getTableInfo: getTableInfo,
    getActionPlayer: getActionPlayer,
    action: action
  };

  blindUp = function() {
    level += 1;
    return setTimeout(function() {
      return blindUp();
    }, intervalTime);
  };

  dealPlayersHands = function(tableId) {
    var cardPosition, i, key, value, _i, _ref;

    tables[tableId].deck = [].concat(createDeck());
    for (i = _i = 0; _i < 2; i = ++_i) {
      _ref = tables[tableId].players;
      for (key in _ref) {
        value = _ref[key];
        cardPosition = Math.floor(Math.random() * tables[tableId].deck.length);
        tables[tableId].players[key].hand[i] = tables[tableId].deck[cardPosition];
        tables[tableId].deck.splice(cardPosition, 1);
        tables[tableId].players[key].isActive = true;
      }
    }
    return console.log('check it!');
  };

  createDeck = function() {
    var trumps;

    trumps = ['As', '2s', '3s', '4s', '5s', '6s', '7s', '8s', '9s', 'Ts', 'Js', 'Qs', 'Ks', 'Ah', '2h', '3h', '4h', '5h', '6h', '7h', '8h', '9h', 'Th', 'Jh', 'Qh', 'Kh', 'Ad', '2d', '3d', '4d', '5d', '6d', '7d', '8d', '9d', 'Td', 'Jd', 'Qd', 'Kd', 'Ac', '2c', '3c', '4c', '5c', '6c', '7c', '8c', '9c', 'Tc', 'Jc', 'Qc', 'Kc'];
    return shuffleArray(trumps);
  };

  shuffleArray = function(targetArray) {
    var j, key, length, t, value;

    length = targetArray.length;
    for (key in targetArray) {
      value = targetArray[key];
      j = Math.floor(Math.random() * length);
      t = '';
      t = value;
      targetArray[j] = '';
      targetArray[j] = value;
      targetArray[key] = '';
      targetArray[key] = t;
    }
    return targetArray;
  };

  shufflePlayers = function(players) {
    var j, key, length, t, value;

    length = players.length;
    for (key in players) {
      value = players[key];
      j = Math.floor(Math.random() * length);
      t = {};
      t = value;
      players[j] = {};
      players[j] = value;
      players[key] = {};
      players[key] = t;
    }
    return players;
  };

}).call(this);
